### ISSUE TITLE
Cordova File transfer example

### ISSUE THREAD

**Issue by janiceParsons** [Dev-Outreach/html-protfolio#11]
I'm not sure where to add a question for the dev<out> group.

But here's my issue... to all developers

One student is making an app using PhoneGap with the Cordana plugins. The file display worked beautifully but we are not getting the FileTransfer one to work.  There is a test.js  in the plugin folders and we would really like a index.html using the four manual test buttons to work to show us how to make it work.  If is works in chrome on Windows 10 that's all we need right away.  We just need the idea.

Thanks a lot.

Janice Parsons
Jasper Place High School - CS teacher

**Comment by mtrebell** [comment]
I'm not fimillar with Cordana, could you please provide some links to the resources you are using?  The links to the js libraries you are using as well as the tutorial you are following, if any please. That'll ensure we have the same copies of all the files. It would also be helpful if you could provide a step by step of what you tried, or if following a tutorial where you got stuck, that way we're on the same page.

**Comment by janiceParsons** [comment]
[JPAPP.zip](https://github.com/Dev-Outreach/html-portfolio/files/1427628/JPAPP.zip)
the index.html file we are using is located in www/index.html

We are trying to do the filetransfer on the admin page located in  www\resources\html\admin.html

under plugins\cordova-plugin-file-transfer-master\tests\tests.js  - Under manual tests, it should build a page with 4 buttons to upload and download.  We're not sure how to call this manual tests.
On line 1632  exports.defineManualTests = function (contentEl, createActionButton) {

Thanks.

**Comment by janiceParsons** [comment]
Well - it is "cordova plugins"  not cordana.  My apologies!!!!

**Comment by mtrebell** [comment]
Ok, I looked at your code.Please let me know if any of this explaination is not clear; The simplest way would be to put the contents of the manual test function into a javascript file (see the sample I attached). 

You had donne this yourself in the html file but it wasn't working for 2 reasons:
Note that I also create the createActionButton function. As far as I can tell, this is not part of Cordova or the Plugin so you need to create one. 

You did not have a call to : document.addEventListener("deviceready", onDeviceReady, false);
The plugin is not available until the decivceReady event is fired, so you want to do work related to it then. 


[tests.zip](https://github.com/Dev-Outreach/html-portfolio/files/1439829/tests.zip)
[sample.zip](https://github.com/Dev-Outreach/html-portfolio/files/1444988/sample.zip)
