### ISSUE TITLE
Web Page Design - Usability and Accessibility 

### ISSUE THREAD

**Issue by mtrebell** [Dev-Outreach/html-protfolio#9]
Create samples of sites that have poor usability for users that are color blind, have poor vision, work poorly with screen readers etc...

Each should be a different page. 

Some links to get started
Introduce tools that can us think about the usability of our sites:
poor contrast: http://www.etre.com/tools/colourcheck/ 
color blindness: http://www.etre.com/tools/colourblindsimulator/
http://colorfilter.wickline.org/

This is intended mainly to be a discussion/exploration exercise, it is something often overlooked when developing apps so we want to just remind students that such problems exist.

**Comment by playerchris** [comment]
I would like to work on this.

Ideas I have are:
Color Blindness - a calendar with red and green text, maybe even colored/highlighted buttons? (to show 'active' buttons?)
Vision - use popups to help make text more visible, allow users to resize text (scrollbar?) when desired, maybe too small buttons/nav items?
Accessibility - too many items in navigation? Or too many items that sound the same?

**Comment by mtrebell** [comment]
In this case Accessibility Refers to poor design in general, including but not limited to poor contrast, poor colour choice and poor aria support. Please re-read the issue, we are concerned with bringing awareness to issues commonly ignored that affect only a portion of the population. Poor Navigation would be a different issue.  Each of these should be a single page not a combination of issues. The intention here is not to create a poorly designed page, but to create a well-designed page with a key accessibility flaw (make a good page better).  Using Red/Green text is a bad choice visually, to begin with so it is not a good example, a better example would be colour coding a calendar square in such a way they are hard to tell apart.

**Comment by playerchris** [comment]
For an Accessibility page then, what about a page that doesn't offer alt text, with a couple of charts that have no descriptive heading?

Or maybe the image without alt text, and a couple paragraphs/articles without headers, so the only way for a user to tell the difference is hearing/reading the content? 
For example: a cupcake recipe with an image, but makes no distinction between the ingredients and the instructions? Or no distinction between directions for the cupcake recipe and the topping recipe?

**Comment by mtrebell** [comment]
Closing this issue in favour of separate better explained issues to keep conversation focused and on track
